### ISSUE TITLE
Looks like devspace sync skip files

### ISSUE THREAD

**Issue by amishurov** [loft-sh/devspace#1296]
**What happened?**  
When I try remove and create many files in project some files skipped. We have precompiled xsl in our project, so it's need:
1. delete already compiled xsl's
2. run xsltroc and get fresh xsl's
after this count local xsl files:
`$ find xhh/xsl_precompiled/  | wc -l
`1179
count pod xsl files:
`# find xhh/xsl_precompiled/  | wc -l
`78
How devspace is running:
`devspace sync --local-path=... --container-path=... --upload-only -e '.git' -e 'python_venv' --verbose`

Then if I restart devspace sync skipped files successfully synced. 

**What did you expect to happen instead?**  
number of files after sync in local dev  = number of files in pod

**How can we reproduce the bug?** (as minimally and precisely as possible)  
need to delete and recreate many files in project directory in short time. I think it's possible using git, i.e. rm project files and then run git reset --hard

**Local Environment:**  
- DevSpace Version: 5.7.1
- Operating System: linux Ubuntu 18.04
- Deployment method: kubectl apply

**Kubernetes Cluster:**  
- Cloud Provider: bare-metal
- Kubernetes Version: Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

**Anything else we need to know?**  

/kind bug

**Comment by FabianKramm** [comment]
@amishurov thanks for reporting this issue! Do you think it might be possible to create a demo repo with which we can reproduce this issue?

**Comment by amishurov** [comment]
Hello, @FabianKramm 
I've added demo repo https://github.com/amishurov/devspace_issue_1296
Howto reproduce bug using this repo:
1.`git clone  git@github.com:amishurov/devspace_issue_1296.git`
2. run `yarn` (I have 1.22.4). It will generates about 55к files
3. run devspace sync `devspace sync --local-path=/home/user/devspace_issue_1296 --container-path=/home/user/devspace_issue_1296 --upload-only -e '.git' --verbose` (initial sync will transfer all files to pod)
4. `rm -rf node_modules && yarn`
5. wait for sync again
6. count files on local file system and in pod:
`find node_modules -type f | wc -l
`57616
`find node_modules -type f | wc -l`
45666

**Comment by FabianKramm** [comment]
@amishurov thanks! I'll take a look and try to reproduce the issue on my machine.

**Comment by FabianKramm** [comment]
@amishurov I tested it and it seems like the internal file system event buffer is overflowing because of the huge amount of changes which results in missing files in the pod. I'll fix this for the next version.

**Comment by amishurov** [comment]
thanks for quick fix, I'll try to test it when release will be ready

**Comment by FabianKramm** [comment]
@amishurov we released v5.7.4, would be great if you could verify that it works. One note: since node_modules contains a lot of symlinks it is possible that the amount of files still differs since devspace does not preserve symlinks and instead resolves them and copies the files instead.

**Comment by amishurov** [comment]
@FabianKramm I've tested new version, and get strange behavior. What i did:
 1. initial sync via `kubectl cp`
 2. `rm -rf node_modules && yarn ` on localhost
 3. wait for sync 
 4. number of files in pod = number of files + number of symlinks on localhost exactly
 5. sleep about 5 min ( had tea :))
 6. repeat p.2-3
 7. got only directories synced, 0 files in pod
 8. restart devspace container
 9 got result as in p.4
 here is devspace sync log (skipped "Symlink found .." messages)
```
 [info]   Start syncing                       
[done] √ Sync started on /project <-> /home/hh/codebase/hh.sites.main (Pod: udev/frontik-865c9857bf-cpfh4)
# first time rm -rf node_modules
[info]   Upstream - Handling 94819 removes
[info]   Upstream - Successfully processed 94819 change(s)
[info]   Upstream - Handling 94 removes
[info]   Upstream - Upload 237000 create change(s) (Uncompressed ~9995077.74 KB)
[info]   Upstream - Successfully processed 237094 change(s)
# second time rm -rf node_modules
[info]   Upstream - Handling 94224 removes
[info]   Upstream - Successfully processed 94224 change(s)
[info]   Upstream - Upload 1981 create change(s) (Uncompressed ~20072.43 KB)
[info]   Upstream - Successfully processed 1981 change(s)
# only directories were synced
# restart devspace here
[info]   Using namespace 'udev'
[info]   Using kube context 'testing.hh.ru'
[info]   Start syncing                       
[done] √ Sync started on /project <-> /home/hh/codebase/hh.sites.main (Pod: udev/frontik-865c9857bf-cpfh4)
[info]   Upstream - Upload 50350 create change(s) (Uncompressed ~221838.23 KB)
[info]   Upstream - Successfully processed 50350 change(s)
[info]   Upstream - Upload 23490 create change(s) (Uncompressed ~198894.35 KB)
[info]   Upstream - Successfully processed 23490 change(s)


```

**Comment by FabianKramm** [comment]
@amishurov thanks for the update! Thats strange, maybe thats another issue, I'll try to reproduce this problem

**Comment by FabianKramm** [comment]
@amishurov I can somewhat reproduce it on linux as when this occurs (after only the folders get synced, for me even only the node_modules folder is synced) the inotify watcher itself seems to completely crash and not notice any events to the synced folders anymore afterwards. Is that the same behaviour for you as well? So basically if your create a file manually in those folders after this happens, does devspace sync that file into the container?

**Comment by amishurov** [comment]
@FabianKramm tried to create file in watched folder and it wasn't synced

**Comment by FabianKramm** [comment]
@amishurov after some investigation I found out that this new problem is indeed an issue of the underlying library that we use (https://github.com/rjeczalik/notify). I opened an issue there and come back to you as soon as there is any progress

**Comment by FabianKramm** [comment]
@amishurov this should be fixed with version v5.9.0

**Comment by amishurov** [comment]
@FabianKramm  thank you! I'll check new version soon

**Comment by amishurov** [comment]
Hello, @FabianKramm, I've just tested version 5.9.0 and looks like problem still reproduced. 
I've tested new version according to my initial issue description, i.e. generated xsl files; than drop all; than generated new ones and waited for sync
and finally got only 15 files&dirs synced instead more than 1k.

**Comment by amishurov** [comment]
Hello @FabianKramm
I've tested version 5.9.0 and got case when file did't sync. In our project we have multiple js files bundled by webpack. Also we have file with meta info about packed js budles. It is xml containing unique hashes i.e
`<?xml version="1.0"?>
<js-variables>
<variable key="appEntryPoint" value="/webpackBuild/appEntryPoint.9a045712a3d479c28c5b.js"/>
</js-variables>
</xml>
`
When developer makes changes in source code this file also changes on the fly by gulp script tracking changes.
Finally, the problem is this file with meta info about bundles doesn't sync into pod. I think this behaviour is effect of many files changing in short time, due webpack working
